[package]
name = "cbf_parser"
version = "0.1.0"
authors = ["Ashcon Mohseninia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.3"
byteorder="1.3.4"