use super::{OperationDelegate, op_funcs::*};

#[derive(Clone)]
pub struct OpCode<'a> {
    pub op_code: u8,
    pub pneumonic: &'a str,
    pub op_func: Option<&'a super::OperationDelegate>,
    pub arg0_is_near_addr: bool
}

impl<'a> std::fmt::Debug for OpCode<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("opCode")
            .field("op_code", &self.op_code)
            .field("pneumonic", &self.pneumonic)
            .field("arg0_is_near_addr", &self.arg0_is_near_addr)
            .finish()
    }
}

impl<'a> OpCode<'a> {
    pub fn new(op_code: u8, pneumonic: &'a str, op_func: Option<&'a super::OperationDelegate>, arg0_is_near_addr: bool) -> Self {
        Self {
            op_code,
            pneumonic,
            op_func,
            arg0_is_near_addr
        }
    }

    pub fn init(op_code: u8, pneumonic: &'a str, op_func: Option<&'a super::OperationDelegate>) -> Self {
        Self {
            op_code,
            pneumonic,
            op_func,
            arg0_is_near_addr: false
        }
    }
}

pub static mut OP_CODE_LIST: &'static[OpCode] = &[
    OpCode {op_code: 0x00, pneumonic: "move", op_func: Some(&op_move), arg0_is_near_addr: false},
    OpCode { op_code: 0x00, pneumonic: "move", op_func: Some(&op_move), arg0_is_near_addr: false},
    OpCode { op_code: 0x01, pneumonic: "clear", op_func: Some(&op_clear), arg0_is_near_addr: false},
    OpCode { op_code: 0x02, pneumonic: "comp", op_func: Some(&op_comp), arg0_is_near_addr: false},
    OpCode { op_code: 0x03, pneumonic: "subb", op_func: Some(&op_subb), arg0_is_near_addr: false},
    OpCode { op_code: 0x04, pneumonic: "adds", op_func: Some(&op_adds), arg0_is_near_addr: false},
    OpCode { op_code: 0x05, pneumonic: "mult", op_func: Some(&op_mult), arg0_is_near_addr: false},
    OpCode { op_code: 0x06, pneumonic: "divs", op_func: Some(&op_divs), arg0_is_near_addr: false},
    OpCode { op_code: 0x07, pneumonic: "and", op_func: Some(&op_and), arg0_is_near_addr: false},
    OpCode { op_code: 0x08, pneumonic: "or",  op_func: Some(&op_or), arg0_is_near_addr: false},
    OpCode { op_code: 0x09, pneumonic: "xor", op_func: Some(&op_xor), arg0_is_near_addr: false},
    OpCode { op_code: 0x0A, pneumonic: "not", op_func: Some(&op_not), arg0_is_near_addr: false},
    OpCode { op_code: 0x0B, pneumonic: "jump", op_func: Some(&op_jump), arg0_is_near_addr: true },
    OpCode { op_code: 0x0C, pneumonic: "jtsr", op_func: None, arg0_is_near_addr: true },
    OpCode { op_code: 0x0D, pneumonic: "ret", op_func: None, arg0_is_near_addr: true },
    OpCode { op_code: 0x0E, pneumonic: "jc", op_func: Some(&op_jc), arg0_is_near_addr: true },      // identical to jb
    OpCode { op_code: 0x0F, pneumonic: "jae", op_func: Some(&op_jae), arg0_is_near_addr: true },    // identical to jnc
    OpCode { op_code: 0x10, pneumonic: "jz", op_func: Some(&op_jz), arg0_is_near_addr: true },
    OpCode { op_code: 0x11, pneumonic: "jnz", op_func: Some(&op_jnz), arg0_is_near_addr: true },
    OpCode { op_code: 0x12, pneumonic: "jv", op_func: Some(&op_jv), arg0_is_near_addr: true },
    OpCode { op_code: 0x13, pneumonic: "jnv", op_func: Some(&op_jnv), arg0_is_near_addr: true },
    OpCode { op_code: 0x14, pneumonic: "jmi", op_func: Some(&op_jmi), arg0_is_near_addr: true },
    OpCode { op_code: 0x15, pneumonic: "jpl", op_func: Some(&op_jpl), arg0_is_near_addr: true },
    OpCode { op_code: 0x16, pneumonic: "clrc", op_func: Some(&op_clrc), arg0_is_near_addr: false},
    OpCode { op_code: 0x17, pneumonic: "setc", op_func: Some(&op_setc), arg0_is_near_addr: false},
    OpCode { op_code: 0x18, pneumonic: "asr", op_func: Some(&op_asr), arg0_is_near_addr: false},
    OpCode { op_code: 0x19, pneumonic: "lsl", op_func: Some(&op_lsl), arg0_is_near_addr: false},
    OpCode { op_code: 0x1A, pneumonic: "lsr", op_func: Some(&op_lsr), arg0_is_near_addr: false},
    OpCode { op_code: 0x1B, pneumonic: "asl", op_func: Some(&op_asl), arg0_is_near_addr: false},
    OpCode { op_code: 0x1C, pneumonic: "nop", op_func: Some(&op_nop), arg0_is_near_addr: false},
    OpCode { op_code: 0x1D, pneumonic: "eoj", op_func: Some(&op_eoj), arg0_is_near_addr: false},
    OpCode { op_code: 0x1E, pneumonic: "push", op_func: Some(&op_push), arg0_is_near_addr: false},
    OpCode { op_code: 0x1F, pneumonic: "pop", op_func: Some(&op_pop), arg0_is_near_addr: false},
    OpCode { op_code: 0x20, pneumonic: "scmp", op_func: Some(&op_scmp), arg0_is_near_addr: false},
    OpCode { op_code: 0x21, pneumonic: "scat", op_func: Some(&op_scat), arg0_is_near_addr: false},
    OpCode { op_code: 0x22, pneumonic: "scut", op_func: Some(&op_scut), arg0_is_near_addr: false},
    OpCode { op_code: 0x23, pneumonic: "slen", op_func: Some(&op_slen), arg0_is_near_addr: false},
    OpCode { op_code: 0x24, pneumonic: "spaste", op_func: Some(&op_spaste), arg0_is_near_addr: false},
    OpCode { op_code: 0x25, pneumonic: "serase", op_func: Some(&op_serase), arg0_is_near_addr: false},
    OpCode { op_code: 0x26, pneumonic: "xconnect", op_func: Some(&op_xconnect), arg0_is_near_addr: false},
    OpCode { op_code: 0x27, pneumonic: "xhangup", op_func: Some(&op_xhangup), arg0_is_near_addr: false},
    OpCode { op_code: 0x28, pneumonic: "xsetpar", op_func: Some(&op_xsetpar), arg0_is_near_addr: false},
    OpCode { op_code: 0x29, pneumonic: "xawlen", op_func: Some(&op_xawlen), arg0_is_near_addr: false},
    OpCode { op_code: 0x2A, pneumonic: "xsend", op_func: Some(&op_xsend), arg0_is_near_addr: false},
    OpCode { op_code: 0x2B, pneumonic: "xsendf", op_func: Some(&op_xsendf), arg0_is_near_addr: false},
    OpCode { op_code: 0x2C, pneumonic: "xrequf", op_func: Some(&op_xrequf), arg0_is_near_addr: false},
    OpCode { op_code: 0x2D, pneumonic: "xstopf", op_func: Some(&op_xstopf), arg0_is_near_addr: false},
    OpCode { op_code: 0x2E, pneumonic: "xkeyb", op_func: Some(&op_xkeyb), arg0_is_near_addr: false},
    OpCode { op_code: 0x2F, pneumonic: "xstate", op_func: Some(&op_xstate), arg0_is_near_addr: false},
    OpCode { op_code: 0x30, pneumonic: "xboot", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x31, pneumonic: "xreset", op_func: Some(&op_xreset), arg0_is_near_addr: false},
    OpCode { op_code: 0x32, pneumonic: "xtype", op_func: Some(&op_xtype), arg0_is_near_addr: false},
    OpCode { op_code: 0x33, pneumonic: "xvers", op_func: Some(&op_xvers), arg0_is_near_addr: false},

    OpCode { op_code: 0x34, pneumonic: "ergb", op_func: Some(&op_ergb), arg0_is_near_addr: false},
    OpCode { op_code: 0x35, pneumonic: "ergw", op_func: Some(&op_ergw), arg0_is_near_addr: false},
    OpCode { op_code: 0x36, pneumonic: "ergd", op_func: Some(&op_ergd), arg0_is_near_addr: false},
    OpCode { op_code: 0x37, pneumonic: "ergi", op_func: Some(&op_ergi), arg0_is_near_addr: false},
    OpCode { op_code: 0x38, pneumonic: "ergr", op_func: Some(&op_ergr), arg0_is_near_addr: false},
    OpCode { op_code: 0x39, pneumonic: "ergs", op_func: Some(&op_ergs), arg0_is_near_addr: false},
    OpCode { op_code: 0x3A, pneumonic: "a2flt", op_func: Some(&op_a2_flt), arg0_is_near_addr: false},
    OpCode { op_code: 0x3B, pneumonic: "fadd", op_func: Some(&op_fadd), arg0_is_near_addr: false},
    OpCode { op_code: 0x3C, pneumonic: "fsub", op_func: Some(&op_fsub), arg0_is_near_addr: false},
    OpCode { op_code: 0x3D, pneumonic: "fmul", op_func: Some(&op_fmul), arg0_is_near_addr: false},
    OpCode { op_code: 0x3E, pneumonic: "fdiv", op_func: Some(&op_fdiv), arg0_is_near_addr: false},
    OpCode { op_code: 0x3F, pneumonic: "ergy", op_func: Some(&op_ergy), arg0_is_near_addr: false},
    OpCode { op_code: 0x40, pneumonic: "enewset", op_func: Some(&op_enewset), arg0_is_near_addr: false},
    OpCode { op_code: 0x41, pneumonic: "etag", op_func: Some(&op_etag), arg0_is_near_addr: true},
    OpCode { op_code: 0x42, pneumonic: "xreps", op_func: Some(&op_xreps), arg0_is_near_addr: false},
    OpCode { op_code: 0x43, pneumonic: "gettmr", op_func: Some(&op_gettmr), arg0_is_near_addr: false},
    OpCode { op_code: 0x44, pneumonic: "settmr", op_func: Some(&op_settmr), arg0_is_near_addr: false},
    OpCode { op_code: 0x45, pneumonic: "sett", op_func: Some(&op_sett), arg0_is_near_addr: false},
    OpCode { op_code: 0x46, pneumonic: "clrt", op_func: Some(&op_clrt), arg0_is_near_addr: false},
    OpCode { op_code: 0x47, pneumonic: "jt", op_func: Some(&op_jt), arg0_is_near_addr: true},
    OpCode { op_code: 0x48, pneumonic: "jnt", op_func: Some(&op_jnt), arg0_is_near_addr: true},

    OpCode { op_code: 0x49, pneumonic: "addc", op_func: Some(&op_addc), arg0_is_near_addr: false},
    OpCode { op_code: 0x4A, pneumonic: "subc", op_func: Some(&op_subc), arg0_is_near_addr: false},
    OpCode { op_code: 0x4B, pneumonic: "break", op_func: Some(&op_break), arg0_is_near_addr: false},
    OpCode { op_code: 0x4C, pneumonic: "clrv", op_func: Some(&op_clrv), arg0_is_near_addr: false},
    OpCode { op_code: 0x4D, pneumonic: "eerr", op_func: Some(&op_eerr), arg0_is_near_addr: false},
    OpCode { op_code: 0x4E, pneumonic: "popf", op_func: Some(&op_popf), arg0_is_near_addr: false},
    OpCode { op_code: 0x4F, pneumonic: "pushf", op_func: Some(&op_pushf), arg0_is_near_addr: false},
    OpCode { op_code: 0x50, pneumonic: "atsp", op_func: Some(&op_atsp), arg0_is_near_addr: false},
    OpCode { op_code: 0x51, pneumonic: "swap", op_func: Some(&op_swap), arg0_is_near_addr: false},
    OpCode { op_code: 0x52, pneumonic: "setspc", op_func: Some(&op_setspc), arg0_is_near_addr: false},
    OpCode { op_code: 0x53, pneumonic: "srevrs", op_func: Some(&op_srevrs), arg0_is_near_addr: false},
    OpCode { op_code: 0x54, pneumonic: "stoken", op_func: Some(&op_stoken), arg0_is_near_addr: false},
    OpCode { op_code: 0x55, pneumonic: "parb", op_func: Some(&op_parl), arg0_is_near_addr: false},
    OpCode { op_code: 0x56, pneumonic: "parw", op_func: Some(&op_parl), arg0_is_near_addr: false},
    OpCode { op_code: 0x57, pneumonic: "parl", op_func: Some(&op_parl), arg0_is_near_addr: false},
    OpCode { op_code: 0x58, pneumonic: "pars", op_func: Some(&op_pars), arg0_is_near_addr: false},
    OpCode { op_code: 0x59, pneumonic: "fclose", op_func: Some(&op_f_close), arg0_is_near_addr: false},

    OpCode { op_code: 0x5A, pneumonic: "jg", op_func: Some(&op_jg), arg0_is_near_addr: true},
    OpCode { op_code: 0x5B, pneumonic: "jge", op_func: Some(&op_jge), arg0_is_near_addr: true},
    OpCode { op_code: 0x5C, pneumonic: "jl", op_func: Some(&op_jl), arg0_is_near_addr: true},
    OpCode { op_code: 0x5D, pneumonic: "jle", op_func: Some(&op_jle), arg0_is_near_addr: true},
    OpCode { op_code: 0x5E, pneumonic: "ja", op_func: Some(&op_ja), arg0_is_near_addr: true},
    OpCode { op_code: 0x5F, pneumonic: "jbe", op_func: Some(&op_jbe), arg0_is_near_addr: true},
    OpCode { op_code: 0x60, pneumonic: "fopen", op_func: Some(&op_f_open), arg0_is_near_addr: false},
    OpCode { op_code: 0x61, pneumonic: "fread", op_func: Some(&op_f_read), arg0_is_near_addr: false},
    OpCode { op_code: 0x62, pneumonic: "freadln", op_func: Some(&op_f_readln), arg0_is_near_addr: false},
    OpCode { op_code: 0x63, pneumonic: "fseek", op_func: Some(&op_f_seek), arg0_is_near_addr: false},
    OpCode { op_code: 0x64, pneumonic: "fseekln", op_func: Some(&op_f_seekln), arg0_is_near_addr: false},
    OpCode { op_code: 0x65, pneumonic: "ftell", op_func: Some(&op_f_tell), arg0_is_near_addr: false},
    OpCode { op_code: 0x66, pneumonic: "ftellln", op_func: Some(&op_f_tellln), arg0_is_near_addr: false},
    OpCode { op_code: 0x67, pneumonic: "a2fix", op_func: Some(&op_a2_fix), arg0_is_near_addr: false},
    OpCode { op_code: 0x68, pneumonic: "fix2flt", op_func: Some(&op_fix_2_flt), arg0_is_near_addr: false},
    OpCode { op_code: 0x69, pneumonic: "parr", op_func: Some(&op_parr), arg0_is_near_addr: false},
    OpCode { op_code: 0x6A, pneumonic: "test", op_func: Some(&op_test), arg0_is_near_addr: false},
    OpCode { op_code: 0x6B, pneumonic: "wait", op_func: Some(&op_wait), arg0_is_near_addr: false},
    OpCode { op_code: 0x6C, pneumonic: "date", op_func: Some(&op_date), arg0_is_near_addr: false},
    OpCode { op_code: 0x6D, pneumonic: "time", op_func: Some(&op_time), arg0_is_near_addr: false},
    OpCode { op_code: 0x6E, pneumonic: "xbatt", op_func: Some(&op_xbatt), arg0_is_near_addr: false},
    OpCode { op_code: 0x6F, pneumonic: "tosp", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x70, pneumonic: "xdownl", op_func: Some(&n_noneull), arg0_is_near_addr: false},
    OpCode { op_code: 0x71, pneumonic: "xgetport", op_func: Some(&op_xgetport), arg0_is_near_addr: false},
    OpCode { op_code: 0x72, pneumonic: "xignit", op_func: Some(&op_xignit), arg0_is_near_addr: false},
    OpCode { op_code: 0x73, pneumonic: "xloopt", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x74, pneumonic: "xprog", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x75, pneumonic: "xraw", op_func: Some(&op_xraw), arg0_is_near_addr: false},
    OpCode { op_code: 0x76, pneumonic: "xsetport", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x77, pneumonic: "xsireset", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x78, pneumonic: "xstoptr", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x79, pneumonic: "fix2hex", op_func: Some(&op_fix_2_hex), arg0_is_near_addr: false},
    OpCode { op_code: 0x7A, pneumonic: "fix2dez", op_func: Some(&op_fix_2_dez), arg0_is_near_addr: false},
    OpCode { op_code: 0x7B, pneumonic: "tabset", op_func: Some(&op_tabset), arg0_is_near_addr: false},
    OpCode { op_code: 0x7C, pneumonic: "tabseek", op_func: Some(&op_tabseek), arg0_is_near_addr: false},
    OpCode { op_code: 0x7D, pneumonic: "tabget", op_func: Some(&op_tabget), arg0_is_near_addr: false},
    OpCode { op_code: 0x7E, pneumonic: "strcat", op_func: Some(&op_strcat), arg0_is_near_addr: false},
    OpCode { op_code: 0x7F, pneumonic: "pary", op_func: Some(&op_pary), arg0_is_near_addr: false},
    OpCode { op_code: 0x80, pneumonic: "parn", op_func: Some(&op_parn), arg0_is_near_addr: false},
    OpCode { op_code: 0x81, pneumonic: "ergc", op_func: Some(&op_ergc), arg0_is_near_addr: false},
    OpCode { op_code: 0x82, pneumonic: "ergl", op_func: Some(&op_ergl), arg0_is_near_addr: false},
    OpCode { op_code: 0x83, pneumonic: "tabline", op_func: Some(&op_tabline), arg0_is_near_addr: false},
    OpCode { op_code: 0x84, pneumonic: "xsendr", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x85, pneumonic: "xrecv", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x86, pneumonic: "xinfo", op_func: None, arg0_is_near_addr: false},
    /*
    OpCode { op_code: 0x87, pneumonic: "flt2a", op_func: Some(&op_flt_2a), arg0_is_near_addr: false},
    OpCode { op_code: 0x88, pneumonic: "setflt", op_func: Some(&op_setflt), arg0_is_near_addr: false},
    OpCode { op_code: 0x89, pneumonic: "cfgig", op_func: Some(&op_cfgig), arg0_is_near_addr: false},
    OpCode { op_code: 0x8A, pneumonic: "cfgsg", op_func: Some(&op_cfgsg), arg0_is_near_addr: false},
    OpCode { op_code: 0x8B, pneumonic: "cfgis", op_func: Some(&op_cfgis), arg0_is_near_addr: false},
    OpCode { op_code: 0x8C, pneumonic: "a2y", op_func: Some(&op_a2y), arg0_is_near_addr: false},
    OpCode { op_code: 0x8D, pneumonic: "xparraw", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0x8E, pneumonic: "hex2y", op_func: Some(&op_hex_2y), arg0_is_near_addr: false},
    OpCode { op_code: 0x8F, pneumonic: "strcmp", op_func: Some(&op_strcmp), arg0_is_near_addr: false},
    OpCode { op_code: 0x90, pneumonic: "strlen", op_func: Some(&op_strlen), arg0_is_near_addr: false},
    OpCode { op_code: 0x91, pneumonic: "y2bcd", op_func: Some(&op_y2_bcd), arg0_is_near_addr: false},
    OpCode { op_code: 0x92, pneumonic: "y2hex", op_func: Some(&op_y2_hex), arg0_is_near_addr: false},
    OpCode { op_code: 0x93, pneumonic: "shmset", op_func: Some(&op_shmset), arg0_is_near_addr: false},
    OpCode { op_code: 0x94, pneumonic: "shmget", op_func: Some(&op_shmget), arg0_is_near_addr: false},
    OpCode { op_code: 0x95, pneumonic: "ergsysi", op_func: Some(&op_ergsysi), arg0_is_near_addr: false},
    OpCode { op_code: 0x96, pneumonic: "flt2fix", op_func: Some(&op_flt2Fix), arg0_is_near_addr: false},
    OpCode { op_code: 0x97, pneumonic: "iupdate", op_func: Some(&op_iupdate), arg0_is_near_addr: false},
    OpCode { op_code: 0x98, pneumonic: "irange", op_func: Some(&op_irange), arg0_is_near_addr: false},
    OpCode { op_code: 0x99, pneumonic: "iincpos",op_func:  Some(&op_iincpos), arg0_is_near_addr: false},
    OpCode { op_code: 0x9A, pneumonic: "tabseeku", op_func: Some(&op_tabseeku), arg0_is_near_addr: false},
    OpCode { op_code: 0x9B, pneumonic: "flt2y4", op_func: Some(&op_flt_2_y4), arg0_is_near_addr: false},
    OpCode { op_code: 0x9C, pneumonic: "flt2y8", op_func: Some(&op_flt_2_y8), arg0_is_near_addr: false},
    OpCode { op_code: 0x9D, pneumonic: "y42flt", op_func: Some(&op_y42_flt), arg0_is_near_addr: false},
    OpCode { op_code: 0x9E, pneumonic: "y82flt", op_func: Some(&op_y82_flt), arg0_is_near_addr: false},
    OpCode { op_code: 0x9F, pneumonic: "plink", op_func: Some(&op_plink), arg0_is_near_addr: false},
    OpCode { op_code: 0xA0, pneumonic: "pcall", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xA1, pneumonic: "fcomp", op_func: Some(&op_fcomp), arg0_is_near_addr: false},
    OpCode { op_code: 0xA2, pneumonic: "plinkv", op_func: Some(&op_plinkv), arg0_is_near_addr: false},
    OpCode { op_code: 0xA3, pneumonic: "ppush", op_func: Some(&op_ppush), arg0_is_near_addr: false},
    OpCode { op_code: 0xA4, pneumonic: "ppop", op_func: Some(&op_ppop), arg0_is_near_addr: false},
    OpCode { op_code: 0xA5, pneumonic: "ppushflt", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xA6, pneumonic: "ppopflt", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xA7, pneumonic: "ppushy", op_func: Some(&op_ppushy), arg0_is_near_addr: false},
    OpCode { op_code: 0xA8, pneumonic: "ppopy", op_func: Some(&op_ppopy), arg0_is_near_addr: false},
    OpCode { op_code: 0xA9, pneumonic: "pjtsr", op_func: Some(&op_pjtsr), arg0_is_near_addr: false},
    OpCode { op_code: 0xAA, pneumonic: "tabsetex", op_func: Some(&op_tabsetex), arg0_is_near_addr: false},
    OpCode { op_code: 0xAB, pneumonic: "ufix2dez", op_func: Some(&op_ufix2Dez), arg0_is_near_addr: false},
    OpCode { op_code: 0xAC, pneumonic: "generr", op_func: Some(&op_generr), arg0_is_near_addr: false},
    OpCode { op_code: 0xAD, pneumonic: "ticks", op_func: Some(&op_ticks), arg0_is_near_addr: false},
    OpCode { op_code: 0xAE, pneumonic: "waitex", op_func: Some(&op_waitex), arg0_is_near_addr: false},
    OpCode { op_code: 0xAF, pneumonic: "xopen", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xB0, pneumonic: "xclose", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xB1, pneumonic: "xcloseex", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xB2, pneumonic: "xswitch", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xB3, pneumonic: "xsendex", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xB4, pneumonic: "xrecvex", op_func: None, arg0_is_near_addr: false},
    OpCode { op_code: 0xB5, pneumonic: "ssize", op_func: Some(&op_ssize), arg0_is_near_addr: false},
    OpCode { op_code: 0xB6, pneumonic: "tabcols", op_func: Some(&op_tabcols), arg0_is_near_addr: false},
    OpCode { op_code: 0xB7, pneumonic: "tabrows", op_func: Some(&op_tabrow), arg0_is_near_addr: false},
    */
];