name: Windows i686 App

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: "app_rust"

jobs:
  build:
    name: stable - windows-latest - i686 - node@14
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Init Macchina module
      run: git submodule update --init --recursive
      
    - name: Install i686 toolchain
      run: rustup target add i686-pc-windows-msvc
    
    - name: Build/release App
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
