name: Linux x64 app

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: "app_rust"

jobs:
  build:
    name: Linux x64 app
    runs-on: ubuntu-latest

    steps:
    - name: Build/release App
      uses: actions-rs/cargo@v1
      with:
        working-directory: "app_rust"
        command: build
        args: --release
